### PR TITLE
Create 264.line breakpoint function module

### LINKED ISSUE #6: Create breakpoint function module
Create module to allow creation of breakpoint functions to control module parameters.

Whiteboard notes from 31/8/2016

### PR DESCRIPTION
**Pull request by delucis**
Closes #6

### CODE REVIEW

**Comment by delucis** [comment]
@jsbean Would you mind pulling this PR branch and seeing if the new `264.line` module works well on your end?

I think the following should do it:

```sh
cd ~/Documents/Max\ 7/Packages
git clone -b feat/6 https://github.com/mus264/264-tools.git
```

**Comment by delucis** [comment]
@jsbean Any chance you’ll have time to look at this and we can get it merged?

**Comment by delucis** [comment]
@jsbean 👍👎?

**Comment by jsbean** [comment]
(Sorry for the delay). This is great! Works beautifully on my end.

One question re: `random`: would it make sense if the random points are laid out from `0` to `127` on the `x` axis? That is, it seems like the `x` value is randomized as well, but maybe it would be more immediately usable if the first `x` value starts right at `0`. 

Perhaps (after this is merged) there could be a progressively disclosed option to indicate the range of randomness, with a default of being scaled along the `x` axis.

**Comment by delucis** [comment]
@jsbean So the default would be to divide the x-axis into equal intervals? Or just that points `0` and `n` should clip to the extremes? I guess my reasoning was that this generates less predictable curves, but maybe more regular spacing in time could be useful as you suggest.

**Comment by jsbean** [comment]
I wasn’t thinking splitting into equal intervals, but rather that point 1 would be at x=0, and point n would be at x=127, with the random distribution of x values of the remaining points scaled accordingly.

**Pull request merged**
